### ISSUE TITLE
Erroneous Fedora 30 image on DockerHub (is Fedora 28)

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-cbi/dockerfiles#10]
```
mistria@mistria-rh:~/git/wildwebdeveloper$ docker pull eclipsecbi/fedora-gtk3-mutter:30-gtk3.24
30-gtk3.24: Pulling from eclipsecbi/fedora-gtk3-mutter
Digest: sha256:f1dbd9ba9408c37c61fa354847ee77717cfaf4c9af8c3ead8d43a9902e469840
Status: Downloaded newer image for eclipsecbi/fedora-gtk3-mutter:30-gtk3.24
docker.io/eclipsecbi/fedora-gtk3-mutter:30-gtk3.24

mistria@mistria-rh:~/git/wildwebdeveloper$ docker run eclipsecbi/fedora-gtk3-mutter:30-gtk3.24 cat /etc/os-release
NAME=Fedora
VERSION="28 (Twenty Eight)"
ID=fedora
VERSION_ID=28
VERSION_CODENAME=""
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Twenty Eight)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```

**Comment by mickaelistria** [comment]
cc @akurtakov 
FWIW, I could build the fedora-gtk3-mutter:30-gtk3.24 locally and then build a downstream image for the Wild Web Developer build; which I published at https://cloud.docker.com/u/mickaelistria/repository/docker/mickaelistria/fedora-gtk3-mutter-java-node . With that image, I can update Wild Web Developer build and enjoy some goodness.

**Comment by akurtakov** [comment]
Smth wnet wrong with the docker push. I reported in the pull request https://github.com/eclipse-cbi/dockerfiles/pull/8

**Comment by akurtakov** [comment]
@mbarbero @fredg02  Any guess what is going wrong ?

**Comment by mbarbero** [comment]
No guess for now. Fedora 28 is picked for images 28, 29 and 30 for no reasons. I've cleared the docker cache and the buildkit cache but it does not change anything. Dockerfiles looks correct to me (the FROM directive refers to proper parent, and when pulled from docker hub repo, it's really fedora 28, 29 and 30).

In the meantime, feel free to build and use your own image pushed on your own dockerhub repo.

**Comment by mickaelistria** [comment]
I confirm Dockerfile is OK because to build my Wild Web Developer image, I did pick the Dockerfile from this repo, built and tagged it locally and then used the resulting image in a `FROM` (see https://github.com/eclipse/wildwebdeveloper/blob/master/docker/Dockerfile#L1 ) and the resulting image pushed to GitHub is a proper Fedora 30.
I believe the process or scripts you've used for building or pushing have a bug.

**Comment by mbarbero** [comment]
Fixed.

```
$ docker run -it --rm eclipsecbi/fedora-gtk3-mutter:30-gtk3.24 cat /etc/os-release | grep PRETTY_NAME 
PRETTY_NAME="Fedora 30 (Container Image)"
$ docker run -it --rm eclipsecbi/fedora-gtk3-mutter:29-gtk3.24 cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Fedora 29 (Container Image)"
$ docker run -it --rm eclipsecbi/fedora-gtk3-mutter:28-gtk3.22 cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Fedora 28 (Twenty Eight)"
```
