### ISSUE TITLE
.vnc content missing in eclipsecbi/ubuntu-gtk3-metacity:18.10-gtk3.24

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-cbi/dockerfiles#2]
This image seems to have no .vnc folder (despite being configured to have one), leading to Xvnc jenkins plugin failing the build.
You can tweak this job and play with the Pipeline to add some `ls` here and there and see that no `.vnc` folder can be found where expected.

**Comment by mickaelistria** [comment]
I think this should actually be more something to improve on the Jenkins Xvnc plugin. Some option like `generatePasswordIfNotExisting=true` would be welcome.

**Comment by mbarbero** [comment]
Maybe, feel free to raise the issue at the Xvnc plugin level. In the meantime, I'll fix this at our level ;)

**Comment by mbarbero** [comment]
I just pushed new version of the images with HOME=/home/vnc instead of /home/jenkins

https://hub.docker.com/r/eclipsecbi/ubuntu-gtk3-metacity/tags
https://hub.docker.com/r/eclipsecbi/debian-gtk3-metacity/tags

Could you please give it a try? Thanks.

**Comment by mickaelistria** [comment]
I've found a workaround (generating the .vnc/passwd as a step in Jenkinsfile) and have moved to other things. I don't think I'm going to try it as this already cost me a lot of time yesterday; but feel free to have fun with https://jenkins.eclipse.org/wildwebdeveloper/job/testDockerXvnc/configure which should be a good starting point for testing.
