### ISSUE TITLE
Please create Fedora gtk3 images

### ISSUE THREAD

**Issue by akurtakov** [eclipse-cbi/dockerfiles#4]
Fedora ships pure(unmodified) GTK stack making it extremely useful when having to verify and report smth upstream to GTK developers.

**Comment by mbarbero** [comment]
Which versions would be useful? AFAICT, here are the mappings between fedora version and gtk versions

Fedora 24 => GTK 3.20.10
Fedora 25 => GTK 3.22.17
Fedora 26 => GTK 3.22.21
Fedora 27 => GTK 3.22.26
Fedora 28 => GTK 3.22.30
Fedora 29 => GTK 3.24.1

**Comment by akurtakov** [comment]
I think we should not give too many options so Fedora 29 for sure, Fedora 28 - 50/50 for me and rest don't bother with them.

**Comment by mbarbero** [comment]
Done. images have been published to docker hub https://hub.docker.com/r/eclipsecbi/fedora-gtk3-mutter/tags
