### ISSUE TITLE
eclipsecbi/jenkins-jnlp-agent fails to start

### ISSUE THREAD

**Issue by bshannon** [eclipse-cbi/dockerfiles#5]
To debug a problem, I'm trying to run the eclipsecbi/jenkins-jnlp-agent
docker image on my own machine.  Unfortunately, it fails to start:

$ sudo docker run -it eclipsecbi/jenkins-jnlp-agent
standard_init_linux.go:190: exec user process caused "permission denied"

The problem is that the uid_entrypoint script is mode 744, owned by root,
and thus not executable by the default user.

In the Dockerfile, change

    RUN chmod u+x /usr/local/bin/uid_entrypoint && \

to

    RUN chmod +x /usr/local/bin/uid_entrypoint && \

**Comment by mbarbero** [comment]
Thanks for the report, patch is coming.

**Comment by mbarbero** [comment]
No need to make executable by all users, just by user with groupId=0. 

New images are deployed to https://hub.docker.com/r/eclipsecbi/jenkins-jnlp-agent/tags
