### ISSUE TITLE
Issues with .vnc folder

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-cbi/dockerfiles#6]
Using new `fedora-gtk3-mutter:29-gtk3.24` image, I see `/home/jenkins/workspace/testDockerXvnc@tmp/durable-3bb33cba/script.sh: line 2: /home/vnc/.vnc/passwd: Permission denied` when trying to generate a password for Xvnc: https://jenkins.eclipse.org/wildwebdeveloper/job/testDockerXvnc/20/console .
So I try to remove this line about the password as it's supposed to be fixed in the Docker image directly; and I see
```
Starting xvnc
Executing shell script inside container [container] of pod [cbi-xvnc-test-4-fg6sm-t4cc5]
Executing command: "vncserver" ":64" "-localhost" "-nolisten" "tcp" 
exit
sh: /home/vnc/.vnc/cbi-xvnc-test-4-fg6sm-t4cc5:64.pid: Permission denied
sh: /home/vnc/.vnc/cbi-xvnc-test-4-fg6sm-t4cc5:64.log: Permission denied

cat: '/home/vnc/.vnc/cbi-xvnc-test-4-fg6sm-t4cc5:64.pid': No such file or directory

WARNING: The first attempt to start Xvnc failed, possibly because the font
catalog is not properly configured.  Attempting to determine an appropriate
font path for this system and restart Xvnc using that font path ...
sh: /home/vnc/.vnc/cbi-xvnc-test-4-fg6sm-t4cc5:64.pid: Permission denied
sh: /home/vnc/.vnc/cbi-xvnc-test-4-fg6sm-t4cc5:64.log: Permission denied

cat: '/home/vnc/.vnc/cbi-xvnc-test-4-fg6sm-t4cc5:64.pid': No such file or directory
Could not start Xvnc.
```
(in test job and actual "production" job).

The change that was implemented for Xvnc in https://github.com/eclipse-cbi/dockerfiles/commit/0067ca3b4854d3ea468b13de507226625ef556fd is actually a major regression. It seems best if it were reverted at the moment and some fixed images republished.
Former a workaround which is to run `mkdir -p ${HOME}/.vnc && echo "123456" | vncpasswd -f > ${HOME}/.vnc/passwd && chmod 600 ${HOME}/.vnc/passwd` during the build (for example in the Jenkinsfile) doesn't work any more.

If you need to test those images, feel free to have fun with https://jenkins.eclipse.org/wildwebdeveloper/job/testDockerXvnc

**Comment by mbarbero** [comment]
Verified with https://jenkins.eclipse.org/wildwebdeveloper/job/testDockerXvnc/22/console
