### ISSUE TITLE
scripts/uid_entrypoint not found when building the image

### ISSUE THREAD

**Issue by kthoms** [eclipse-cbi/dockerfiles#7]
I tried to build the fedora image and run into a problem. Steps to reproduce (Mac/Linux):

```
git clone https://github.com/eclipse-cbi/dockerfiles.git
cd dockerfiles/
docker build fedora-gtk3-mutter/29-gtk3.24/

Step 2/11 : COPY scripts/uid_entrypoint /usr/local/bin/uid_entrypoint
COPY failed: stat /var/lib/docker/tmp/docker-builder378917498/scripts/uid_entrypoint: no such file or directory
```

This can be worked around by copying the scripts directory to the directory containing the Dockerfile (found a hint [here](https://github.com/docker/for-mac/issues/1922)).

```
cp -r scripts/ fedora-gtk3-mutter/29-gtk3.24/scripts
```

But there might be a better solution?

**Comment by mbarbero** [comment]
you need to build from the root folder

docker build -f fedora-gtk3-mutter/29-gtk3.24/Dockerfile .

**Comment by kthoms** [comment]
Thanks for clarification. Still too new with docker :/
